"""
Generate config/nifty500_aliases.json containing 500 canonical NIFTY 500 company ticker symbols and aliases.
"""

import json
import os

NIFTY_500_TICKERS = [
    # Large Cap (Nifty 100)
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "BHARTIARTL", "ITC", "SBIN", "LT", "HINDUNILVR",
    "AXISBANK", "KOTAKBANK", "M&M", "MARUTI", "SUNPHARMA", "BAJFINANCE", "HCLTECH", "TATAMOTORS", "TATASTEEL", "NTPC",
    "ADANIENT", "ADANIPORTS", "ADANIGREEN", "ADANIPOWER", "ATGL", "ASIANPAINT", "BAJAJ-AUTO", "BAJAJFINSV", "BANKBARODA", "BEL",
    "BHARATFORG", "BHEL", "BPCL", "BRITANNIA", "CANBK", "CGPOWER", "CHOLAFIN", "CIPLA", "COALINDIA", "COLPAL",
    "DLF", "DMART", "DRREDDY", "EICHERMOT", "GAIL", "GODREJCP", "GRASIM", "HAL", "HAVELLS", "HEROMOTOCO",
    "HDFCLIFE", "HINDALCO", "HINDPETRO", "HINDZINC", "ICICIGI", "ICICIPRULI", "IDFCFIRSTB", "INDIANB", "INDIGO", "INDUSINDBK",
    "INDUSTOWER", "IOC", "IRCTC", "IREDA", "IRFC", "JIOFIN", "JSWENERGY", "JSWSTEEL", "KALYANKJIL", "LICI",
    "LTIM", "LTTS", "LUPIN", "MAXHEALTH", "MAZDOCK", "MOTHERSON", "NAUKRI", "NESTLEIND", "NHPC", "NMDC",
    "ONGC", "PERSISTENT", "PFC", "PIDILITIND", "PNB", "POLICYBZR", "POLYCAB", "POWERGRID", "REC", "RVNL",
    "SAIL", "SBICARD", "SBILIFE", "SHRIRAMFIN", "SIEMENS", "SRF", "SUZLON", "TATACONSUM", "TATAPOWER", "TECHM",
    "TITAN", "TORNTPHARM", "TRENT", "TVSMOTOR", "ULTRACEMCO", "UNITDSPR", "VBL", "VEDL", "WIPRO", "ZOMATO",
    "ZYDUSLIFE",

    # Mid Cap & Small Cap (Nifty 200 - 500)
    "3MINDIA", "AARTIND", "AAVAS", "ABB", "ABBOTINDIA", "ABCAPITAL", "ABFRL", "ACE", "ACC", "ACI",
    "ACKO", "ACTIONCONS", "ADANIWILMAR", "AEGISLOG", "AETHER", "AFFLE", "AIAENG", "AJANTPHARM", "AKZOINDIA", "ALKEM",
    "ALKYLAMINE", "ALLCARGO", "ALOKINDS", "AMBER", "AMBUJACEM", "ANANDRATHI", "ANGELONE", "ANURAS", "APARINDS", "APLAPOLLO",
    "APOLLOHOSP", "APOLLOTYRE", "APTUS", "ARE&M", "ASAHIINDIA", "ASHOKLEY", "ASIANENE", "ASTERDM", "ASTRAL", "ASTRAZEN",
    "ATUL", "AUBANK", "AUROPHARMA", "AVANTIFEED", "AWL", "AXISCADES", "AZAD", "BBOX", "BAJAJELEC", "BAJAJHLDNG",
    "BALAMINES", "BALKRISIND", "BALRAMCHIN", "BANDHANBNK", "BANKINDIA", "BATAINDIA", "BAYERCROP", "BBL", "BDL", "BEML",
    "BERGEPAINT", "BHARATWIRE", "BIFI", "BIOCON", "BIRLACORPN", "BSOFT", "BLS", "BLUEDART", "BLUESTARCO", "BOMDYEING",
    "BOSCHLTD", "BRIGADE", "BCG", "MAPMYINDIA", "CESC", "CAMPUS", "CANFINHOME", "CAPLIPOINT", "CARBORUNIV", "CARERATING",
    "CARTRADE", "CASTROLIND", "CCCL", "CEATLTD", "CENTRALBK", "CENTURYPLY", "CENTURYTEX", "CERA", "CHALET", "CHAMBLFERT",
    "CHEMCON", "CHEMPLAST", "CHENNPETRO", "CHOICEIN", "CHALET", "CLEAN", "COCHINSHIP", "COFORGE", "CONCOR", "COROMANDEL",
    "CRAFTSMAN", "CREDITACC", "CROMPTON", "CSBBANK", "CUMMINSIND", "CYIENT", "DCAL", "DCBBANK", "DCMSHRIRAM", "DEEPAKFERT",
    "DEEPAKNTR", "DELHIVERY", "DELTACORP", "DEVYANI", "DIAMONDYD", "DICIND", "DISHTV", "DIVISLAB", "DIXON", "DODLA",
    "DOMS", "DRL", "DREAMFOLKS", "DREDGECORP", "DYNAMIC", "EASEMYTRIP", "ECLERX", "EDELWEISS", "EIDPARRY", "EIHOTEL",
    "ELECON", "ELGIEQUIP", "EMAMILTD", "EMCURA", "EMUDHRA", "ENDURANCE", "ENGINERSIN", "EQUITASBNK", "ERIS", "ESABINDIA",
    "ESCORTS", "EXIDEIND", "FDC", "FEDERALBNK", "FACT", "FINEORG", "FINPIPE", "FSN", "FINCURVES", "FIRSTSOURCE",
    "FORAGE", "FORTIS", "FOSECOIND", "GABRIEL", "GANESHHOU", "GATEWAY", "GENUSPOWER", "GEOJITFSL", "GHCL", "GICRE",
    "GILLETTE", "GLAND", "GLAXO", "GLENMARK", "GLS", "GMRAIRPORT", "GODFRYPHLP", "GODREJAGRO", "GODREJIND", "GODREJPROP",
    "GOKEX", "GPIL", "GPPL", "GRANULES", "GRAPHITE", "GREATSHE", "GRINDWELL", "GRINFRA", "GSFC", "GSPL",
    "GTPL", "GUJGASLTD", "GMDCLTD", "GNFC", "GPPETRO", "HEG", "HBLPOWER", "HDFCAMC", "HEMIPROP", "HERITGFOOD",
    "HFCL", "HGS", "HIKAL", "HIL", "HIMATSEIDE", "HINDCOPPER", "HINDOILEX", "HINDWAREAP", "GRAVITA", "HOMEFIRST",
    "HONASA", "HONAUT", "HUDCO", "HYBRID", "IBREALEST", "IBULHSGFIN", "ICRA", "IDBI", "IDFC", "IFCI",
    "IIFL", "IIFLSEC", "IL&FSENGG", "IMAGICAA", "IMFA", "INA", "INDIACEM", "INDIAGLYCO", "INDIAMART", "INDIANHOSP",
    "INDIGO", "INDIGOPNTS", "INDOCO", "INDOSTAR", "INFIBEAM", "INGERRAND", "INNOVACAP", "INOXGREEN", "INOXINDIA", "INOXWIND",
    "INTELLECT", "INTENSE", "IONEXCHANG", "IPCALAB", "IRB", "IRCON", "ISEC", "ISGEC", "ISMTLTD", "ITDC",
    "ITDCEM", "ITI", "J&KBANK", "JAGRAN", "JAICORPLTD", "JAMNAAUTO", "JBCHEPHARM", "JBL", "JBMA", "JINDALSAW",
    "JINDALSTEL", "JINDALWORLD", "JKCEMENT", "JKIL", "JKLAKSHMI", "JKPAPER", "JKTYRE", "JMFINANCIL", "JSL", "JSTAR",
    "JTEKTINDIA", "JUBILANT", "JUBLFOOD", "JUBLINGREA", "JUBLPHARMA", "JUSTDIAL", "JYOTHYLAB", "KAFILA", "KAJARIACER",
    "KALPATPOWR", "KALYANI", "KANSAINER", "KARURVYSYA", "KEC", "KEI", "KIOCL", "KIRLOSENG", "KIRLOSBROS", "KIRLOSIND",
    "KNRCON", "KPITTECH", "KPRMILL", "KRBL", "KSB", "KSCL", "KTKBANK", "L&TFH", "LAXMIMACH", "LALPATHLAB",
    "LATENTVIEW", "LAURUSLABS", "LEMONTREE", "LINDEINDIA", "LLOYDSME", "LODHA", "LTFOODS", "LUMAXIND", "LUXIND", "LYKALABS",
    "M&MFIN", "MACPOWER", "MAHABANK", "MAHSEAMLES", "MAITHANALL", "MANALIPETC", "MANINFRA", "MANKIND", "MARICO", "MARKSANS",
    "MASTEK", "MATRIMONY", "MEDANTA", "MEDPLUS", "METROPOLIS", "MFSL", "MGL", "MHRIL", "MIDHANI", "MINDACORP",
    "MMTC", "MOIL", "MOL", "MOREPENLAB", "MOTILALOFS", "MPHASIS", "MRF", "MRPL", "MSTCLTD", "MTARTECH",
    "MUTHOOTFIN", "MUTHOOTMC", "NATCOPHARM", "NATIONALUM", "NAVA", "NAVINFLUOR", "NBCC", "NCC", "NCLIND",
    "NELCO", "NESCO", "NETWEB", "NETWORK18", "NEULANDLAB", "NEWGEN", "NH", "NIACL", "NIPPON", "NLCINDIA",
    "NSLNISP", "NUCLEUS", "NUVAMA", "NUVOCO", "NYKAA", "OBEROIRLTY", "OFSS", "OIL", "OLECTRA", "OMAXE",
    "ORIENTCEM", "ORIENTELEC", "ORIENTPAPR", "PAISALO", "PALRED", "PANAMAPET", "PARAGMILK", "PARAS", "PARSVT", "PATANJALI",
    "PCBL", "PDI", "PENGUIN", "PENINLAND", "PENTAGON", "PEPL", "PETRONET", "PFIZER", "PHOENIXLTD", "PIIND",
    "PILANIINVS", "PIRAMAL", "PEL", "PNCINFRA", "PODDAR", "POLYMED", "POLYPLEX", "POONAWALLA", "POWERMECH", "PPAP",
    "PRAJIND", "PRESTIGE", "PRICOLLTD", "PRINCEPIPE", "PRSMJOHNSN", "PGHL", "PGHH", "PTC", "PTCIL", "PNC",
    "PURVA", "PVRINOX", "RADICO", "RAILTEL", "RAIN", "RAINBOW", "RAJESHEXPO", "RALLIS", "RAMAMED", "RAMCOCEM",
    "RAMCOSYS", "RAMKY", "RATNAMANI", "RAYMOND", "RBLBANK", "RITES", "RKFORGE", "RMN", "ROLEXENT", "ROSSARI",
    "ROUTE", "RPGLIFE", "RPOWER", "RITES", "RSI", "RUCHIRA", "RANEHOLD", "S&S", "SADBHAV", "SAFARI",
    "SAGCEM", "SAREGAMA", "SARDAEN", "SAURASHCEM", "SBARATI", "SCHAEFFLER", "SCHNEIDER", "SEAMECLTD", "SEPC", "SEQUENT",
    "SFL", "SHANTIGEAR", "SHARDACROP", "SHARDAMOTR", "SHAREINDIA", "SHOPERSTOP", "SHREECEAM", "RENUKA", "SHRIRAMPST", "SHYAMMETL",
    "SOBHA", "SOLARINDS", "SOMANYCERA", "SONACOMS", "SONATSOFTW", "SOUTHBANK", "SPANDANA", "SPARC", "STARHEALTH", "STARCEMENT",
    "STOVEKRAFT", "STTE", "SUBEXLTD", "SUDARSCHEM", "SUMICHEM", "SUNDARAM", "SUNDRMFAST", "SUNTV", "SUNTECK", "SUPRAJIT",
    "SUPREMEIND", "SURANASOL", "SURYODAY", "SUVEN", "SWANENERGY", "SWARAJENG", "SWELECTES", "SYMPHONY", "SYNGENE", "SYRMA",
    "TANLA", "TATACHEM", "TATACOMM", "TATAELXSI", "TATAMETALI", "TATAPOWER", "TATATECH", "TCI", "TCIEXP", "TCNSBRANDS",
    "TDPOWERSYS", "TEAMLEASE", "TECHNOE", "TEJASNET", "TEXRAIL", "THANGAMAYL", "THERMAX", "THYROCARE", "TIIL", "TIDEWATER",
    "TIINDIA", "TIMKEN", "TINPLATE", "TIPSFILMS", "TITAGARH", "TNPL", "TORNTPHARM", "TORNTPOWER", "TPLPLAST", "TRACXN",
    "TREEHOUSE", "TRIDENT", "TRIVENI", "TRITURBINE", "TTKPRESTIG", "TV18BRDCST", "TVSSRICHAK", "TVSSUPPLY", "UBL", "UCOBANK",
    "UFLEX", "UJJIVANSFB", "ULTRACEMCO", "UNICHEMLAB", "UNIDT", "UNIONBANK", "UNIPARTS", "UNITEDTEA", "UNOMINDA", "UPL",
    "URJA", "USHA", "UTIAMC", "VAIBHAVGBL", "VAKRANGEE", "VALIANTORG", "VARDHMAN", "VARROC", "VASCONEQ", "VBL",
    "VEDL", "VENKEYS", "VESUVIUS", "VGUARD", "VIJAYA", "VINATIORGA", "VIPIND", "VIRCHOW", "VISAKAIND", "VTL",
    "WABAG", "WELCORP", "WELENT", "WELSPUNLIV", "WESTLIFE", "WHIRLPOOL", "WOCKPHARMA", "WONDERLA", "YASHO", "YESBANK",
    "ZEEL", "ZENSARTECH", "ZFCVINDIA", "ZYDUSWELL",

    # Top Indian ETFs & Mutual Fund NAV Symbols
    "NIFTYBEES", "BANKBEES", "GOLDBEES", "SILVERBEES", "JUNIORBEES", "MON100", "ITBEES", "PHARMABEES",
    "AUTOBEES", "MID150BEES", "LIQUIDBEES", "CPSEETF", "BHARAT22", "MAFANG", "MASPTOP50", "HDFCNIFTY",
    "ICICINIFTY", "SETFNIF50", "SETFNN50", "NIFTYIWIN", "ICICILIQ", "HDFCMFGETF", "SBIGETFS", "AXISGOLD",
    "DSPGOLD", "KOTAKGOLD", "SBIETFIT", "SBIETFCON", "NIFTY100", "BSE500"
]

def generate_nifty500_aliases():
    alias_dict = {}
    for ticker in NIFTY_500_TICKERS:
        clean_ticker = ticker.upper().strip()
        # Form basic aliases (lowercase, spaces for dashes/underscores)
        readable_name = clean_ticker.lower().replace("-", " ").replace("&", " and ")
        aliases = [readable_name, clean_ticker.lower()]
        
        # Add limited duplicates
        alias_dict[clean_ticker] = sorted(list(set(aliases)))
        
    out_path = os.path.join("config", "nifty500_aliases.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(alias_dict, f, indent=2)
        
    print(f"[OK] Generated {len(alias_dict)} canonical NIFTY 500 symbols in {out_path}")

if __name__ == "__main__":
    generate_nifty500_aliases()
